// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4OchQZzEjj2t5xuNZO1TvNLtQYlMQyS4',
    appId: '1:367892879877:web:48ad2771a14b4019049a6c',
    messagingSenderId: '367892879877',
    projectId: 'campusbuzz-936d3',
    authDomain: 'campusbuzz-936d3.firebaseapp.com',
    databaseURL: 'https://campusbuzz-936d3-default-rtdb.firebaseio.com',
    storageBucket: 'campusbuzz-936d3.appspot.com',
    measurementId: 'G-1V38RYCPJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYYlQLX3GPFyUVotPaEZXv4CYHHaqw8yg',
    appId: '1:367892879877:android:6c8199fa14837e51049a6c',
    messagingSenderId: '367892879877',
    projectId: 'campusbuzz-936d3',
    databaseURL: 'https://campusbuzz-936d3-default-rtdb.firebaseio.com',
    storageBucket: 'campusbuzz-936d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PkP31QX0S00lz9B1aUoOSNc2VJcnCwg',
    appId: '1:367892879877:ios:c1db3f744ded2cb9049a6c',
    messagingSenderId: '367892879877',
    projectId: 'campusbuzz-936d3',
    databaseURL: 'https://campusbuzz-936d3-default-rtdb.firebaseio.com',
    storageBucket: 'campusbuzz-936d3.appspot.com',
    androidClientId: '367892879877-8cjspv1j1o0u8hijirvd4ge5s1qr55us.apps.googleusercontent.com',
    iosClientId: '367892879877-anu9j6j0qraqe89nlcobhl4905qsc5fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusbuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_PkP31QX0S00lz9B1aUoOSNc2VJcnCwg',
    appId: '1:367892879877:ios:aeee77b892445d41049a6c',
    messagingSenderId: '367892879877',
    projectId: 'campusbuzz-936d3',
    databaseURL: 'https://campusbuzz-936d3-default-rtdb.firebaseio.com',
    storageBucket: 'campusbuzz-936d3.appspot.com',
    androidClientId: '367892879877-8cjspv1j1o0u8hijirvd4ge5s1qr55us.apps.googleusercontent.com',
    iosClientId: '367892879877-mh5s80stqfk0q35f01tm8oopscgt558v.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusbuzz.RunnerTests',
  );
}
